basePath: /
definitions:
  ds.ErrorResponse:
    properties:
      error:
        example: Некорректный токен
        type: string
    type: object
  ds.LoginReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  ds.LoginResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      expires_in:
        description: время жизни токена (в секундах)
        example: 3600
        type: integer
      token_type:
        example: Bearer
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API сервиса аутентификации с Redis и JWT. Поддерживает роли пользователей
    и администраторов.
  title: Device emission Service API
  version: "1.0"
paths:
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя по логину и паролю, возвращает JWT-токен
        и время жизни
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ds.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.LoginResponse'
        "400":
          description: Неверный формат запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Пользователь не найден или неверный пароль
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Аутентификация пользователя
      tags:
      - auth
  /api/users/logout:
    post:
      description: Добавляет JWT-токен в черный список (блеклист) Redis, чтобы он
        стал недействительным
      produces:
      - application/json
      responses:
        "200":
          description: Успешный выход
        "400":
          description: Некорректный токен
          schema:
            $ref: '#/definitions/ds.ErrorResponse'
        "500":
          description: Ошибка при записи токена в блеклист
          schema:
            $ref: '#/definitions/ds.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Деаутентификация пользователя
      tags:
      - auth
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
